<div class="container clearfix">
  <div class="contacts floatLeft">
    <div class="buttons">
      <button class="new-message fa-envelope-o"></button><button class="search fa-search"></button>
    </div>
    <ul>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ul>
  </div>
  <div class="floatRight">
    <div class="messages">
      <ul>
      <li>
      Is this the real life?
      </li>
      <li>
      Is this just fantasy?
      </li>
      </ul>
    </div>
    <div class="stack-wrap"></div>
    <div class="form">
      <div class="form-inner">
        <button>✚</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="public/scripts/index.js"></script>