<header class="header ">
	<h1>The Tchat
	<br><span>(Si ça marche pas c'est la faute à Kevin)</span></h1>
		<nav class="nav">
			<ul>
				<li>
					<a class="" href="index.php?page=register"><i class="fa fa-hdd-o" aria-hidden="true"></i> S'enregistrer</a>
				</li>
				<li>
					<a class="" href="index.php?page=login"><i class="fa fa-hdd-o" aria-hidden="true"></i> Se connecter</a>
				</li>
				<!-- AJAX - Ne pas supprimer
				<li>
					<form id="form_search">
						<input type="hidden" value="recherche" name="page">
						<input class="search" autofocus type="search" placeholder="Entrez un mot-clé" name="search" onfocus="this.value = this.value;" value="<?=$search?>">
						<input type="submit" style="display:none">
					</form>
				</li>
				-->
			</ul>
		</nav>
</header>
