<header class="header">
	<h1>The Tchat
		<br><span>(Si ça marche pas c'est la faute à Kévin)</span>
		<br><span>(Si c'est moche c'est pas de la faute à Kévin)</span>
	</h1>
	<nav class="nav">
		<ul>
			<li><a class="link-header" href="index.php?page=home">Home</a></li>
			<li><a class="link-header" href="index.php?page=logout"><i class="fa fa-sign-out" aria-hidden="true"></i> Log out</a></li>
			<li>
				<form>
					<input type="hidden" value="recherche" name="page">
					<input class="search" autofocus type="search" placeholder="Utilisez Ctrl+F, lol" name="search" onfocus="this.value = this.value;" value="<?=$search?>">
					<input type="submit" style="display:none">
				</form>
			</li>
			<li><p>Connecté en tant que <?=htmlentities($_SESSION['user'])?></a></li>
		</ul>
	</nav>
</header>