<div class="login">
	<form method="post">
		<h2 class="">Se connecter :</h2>
		<input type="hidden" name="action" value="login">
		<label for="login">Pseudo</label>
		<input type="text" name="login" id="login" placeholder="Choisissez un pseudo" >
		<label for="pwd">Choisissez un mot de passe</label>
		<input type="password" name="pwd" id="pwd" placeholder="Entrez votre mot de passe" >
		<button class="loginButton" type="submit" value="login">Entrer</button>
	</form>
</div>