<form class="" method="post">
	<div class="">
		<h2 class="registerTitle">MES COORDONNEES :</h2>
		
		<input type="hidden" name="action" value="register">
		
		<label for="login">Pseudo</label>
		<input type="text" name="login" id="login" placeholder="Choisissez un pseudo" >
		
		<label for="pwd">Choisissez un mot de passe</label>
		<input type="password" name="pwd" id="pwd" placeholder="Choisissez un mot de passe" >
		
		<label for="pwd2">Confirmez votre mot de passe</label>
		<input type="password" name="pwd2" id="pwd2" placeholder="Confirmez votre mot de passe" >
</form>
