<h2>Register</h2>
<form class="" method="post">
	<h2 class="registerTitle">MES COORDONNEES :</h2>
	
	<input type="hidden" name="action" value="register">
	
	<label for="login">Pseudo</label>
	<input type="text" name="login" id="login" placeholder="Choisissez un pseudo" >
	
	<label for="password">Choisissez un mot de passe</label>
	<input type="password" name="password1" id="password1" placeholder="Choisissez un mot de passe" >
	
	<label for="password2">Confirmez votre mot de passe</label>
	<input type="password" name="password2" id="password2" placeholder="Confirmez votre mot de passe" >
	<button type="submit">Envoyer</button>
</form>