<h1>Register</h1>
<form method="POST">
	<div style="background-color:red;"><?=$error?></div>
	<div class="form-group">
		<label for="exampleInputEmail1">Email address</label>
		<input type="email" required class="form-control" id="exampleInputEmail1" name="email" placeholder="Email">
	</div>
	<div class="form-group">
		<label for="exampleInputLogin">Login</label>
		<input type="text" required class="form-control" id="exampleInputLogin" name="login" placeholder="Login">
	</div>
	<div class="form-group">
		<label for="exampleInputBirthdate">Birthdate</label>
		<input type="date" required class="form-control" id="exampleInputBirthdate" name="birthdate">
	</div>
	<div class="form-group">
		<label>Gender</label>
		<label class="radio-inline">
			<input type="radio" required name="gender" value="0"> Female
		</label>
		<label class="radio-inline">
			<input type="radio" required name="gender" value="1"> Male
		</label>
	</div>
	<div class="form-group">
		<label for="exampleInputPassword1">Password</label>
		<input type="password" required class="form-control" id="exampleInputPassword1" name="password1" placeholder="Password">
	</div>
	<div class="form-group">
		<label for="exampleInputPassword2">Retype Password</label>
		<input type="password" required class="form-control" id="exampleInputPassword2" name="password2" placeholder="Retype Password">
	</div>
	<button type="submit" class="btn btn-default">Register</button>
</form>