<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>Chat</title>
		<link href="public/styles/font-awesome.min.css" rel="stylesheet">
		<!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"> -->
		<!-- <link rel="icon" type="image/x-icon" href="public/images/favicon.ico" /> -->
		<link rel="stylesheet" type="text/css" href="public/styles/reset.css">
		<link rel="stylesheet" type="text/css" href="public/styles/style.css">
		<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css">
		<script type="text/javascript" src="public/scripts/index.js"></script>
	</head>
	<body>
		<?php
			require('controllers/header.php');
			require('controllers/content.php');
			require('controllers/footer.php');
		?>
	</body>
</html>