<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>Chat</title>
		<!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"> -->
		<!-- <link rel="icon" type="image/x-icon" href="public/images/favicon.ico" /> -->
		<link href="https://fonts.googleapis.com/css?family=Pavanam|Yatra+One" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="public/styles/reset.css">
		<!-- <link rel="stylesheet" type="text/css" href="public/styles/reset.css"> -->
		<link rel="stylesheet" type="text/css" href="public/styles/style.css">
		<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css">
		<link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css'>
		<link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Open+Sans'>
		<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/jScrollPane/2.0.14/style/jquery.jscrollpane.min.css'>
		<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/jScrollPane/2.0.14/style/jquery.jscrollpane.min.css'>
	</head>
	<body>
		<?php
			require('controllers/header.php');
			require('controllers/content.php');
			require('controllers/footer.php');
		?>
	<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>
	<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.11/jquery.mousewheel.min.js'></script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/jScrollPane/2.0.14/jquery.jscrollpane.min.js'></script>
	<script type="text/javascript" src="public/scripts/index.js"></script>
	</body>
</html>